export const focusMutations = {
	APP_FOCUS: 'APP_FOCUS',
	APP_BLUR: 'APP_BLUR',
}

export const snippetsMutations  = {
	SAVE_ITEM: 'SAVE_ITEM',
	DELETE_ITEM: 'DELETE_ITEM',
	ADD_EXAMPLES_FOR_TOUR: 'ADD_EXAMPLES_FOR_TOUR',
	TOGGLE_ENCRYPTION: 'TOGGLE_ENCRYPTION',
	SET_HAS_USER_SNIPPETS_FLAG: 'SET_HAS_USER_SNIPPETS_FLAG',
	SET_SNIPPET_DATA: 'SET_SNIPPET_DATA',
}

export const snippetsActions = {
	LOAD: 'LOAD',
	SAVE_ITEM: 'SAVE_ITEM',
	DELETE_ITEM: 'DELETE_ITEM',
	// ADD_EXAMPLES_FOR_TOUR: 'ADD_EXAMPLES_FOR_TOUR',
	// TOGGLE_ENCRYPTION: 'TOGGLE_ENCRYPTION',
}

export const systemActions  = {
	INIT: 'INIT',
	SHOW_BETA_SURVEY: 'SHOW_BETA_SURVEY',

}


export const systemMutations  = {
	LOAD_SETTINGS: 'LOAD_SETTINGS',
	SAVE_SETTING: 'SAVE_SETTING',
	SHOW_PROMPT: 'SHOW_PROMPT',
	CREATE_NEW_TEMPLATE: 'CREATE_NEW_TEMPLATE',
	SHOW_TIPS: 'SHOW_TIPS',
	EDIT_TEMPLATES: 'EDIT_TEMPLATES',
	IMPORT_TEMPLATES: 'IMPORT_TEMPLATES',
	EXPORT_TEMPLATES: 'EXPORT_TEMPLATES',
	GENERAL_SETTINGS: 'GENERAL_SETTINGS',
	SETTINGS_MENU: 'SETTINGS_MENU',
	ABOUT: 'ABOUT',
	RESTART_TOUR: 'RESTART_TOUR',
	CLOSE_CYRUS: 'CLOSE_CYRUS',
	AUTO_START_CYRUS_AT_LOGIN: 'AUTO_START_CYRUS_AT_LOGIN',



	SETTING_CHANGE_LAUNCH_AT_START_UP: 'SETTING_CHANGE_LAUNCH_AT_START_UP',
}

export const categories = {
	CLIPPY: 'CYRUS',
	USER_GENERATED: 'USER_GENERATED',
	IMPORTED: 'IMPORTED'
}
export const tourMutations = {
	START: 'START',
	NEXT_STEP: 'NEXT_STEP',
	CLOSE_TOUR: 'CLOSE_TOUR',
	HIDE_TOUR: 'HIDE_TOUR',
	SHOW_TOUR: 'SHOW_TOUR',
	JUMP_TO_SETTINGS_BIT: 'JUMP_TO_SETTINGS_BIT',
	HAVE_CLICKED_VIDEO_LINK: 'HAVE_CLICKED_VIDEO_LINK',
}

export const searchMutations = {
	SET_SEARCH_TERM: 'SET_SEARCH_TERM'
}

export const analyticsMutations= {
	SET_CLIENT_ID: 'SET_CLIENT_ID',
	GOOGLE_DOWN: 'GOOGLE_DOWN',
}

export const analyticsActions = {
	PAGE_VIEW: 'PAGE_VIEW',
}

export const importExportActions = {
	GENERATE_TEMPLATE: 'GENERATE_TEMPLATE',
	IMPORT_CSV: 'IMPORT_CSV',
}