export const focusMutations = {
	APP_FOCUS: 'APP_FOCUS',
	APP_BLUR: 'APP_BLUR',
}

export const snippetsMutations  = {
	LOAD: 'LOAD',
	SAVE_ITEM: 'SAVE_ITEM',
	DELETE_ITEM: 'DELETE_ITEM',
	ADD_EXAMPLES_FOR_TOUR: 'ADD_EXAMPLES_FOR_TOUR',
}

export const systemMutations  = {
	CREATE_NEW_TEMPLATE: 'CREATE_NEW_TEMPLATE',
	SHOW_TIPS: 'SHOW_TIPS',
	EDIT_TEMPLATES: 'EDIT_TEMPLATES',
	IMPORT_TEMPLATES: 'IMPORT_TEMPLATES',
	EXPORT_TEMPLATES: 'EXPORT_TEMPLATES',
	GENERAL_SETTINGS: 'GENERAL_SETTINGS',
	SETTINGS_MENU: 'SETTINGS_MENU',
	ABOUT: 'ABOUT',
	RESTART_TOUR: 'RESTART_TOUR',
	CLOSE_CYRUS: 'CLOSE_CYRUS',
}

export const categories = {
	CLIPPY: 'CYRUS',
	USER_GENERATED: 'USER_GENERATED',
	IMPORTED: 'IMPORTED'
}
export const tourMutations = {
	START: 'START',
	NEXT_STEP: 'NEXT_STEP',
	CLOSE_TOUR: 'CLOSE_TOUR',
	HIDE_TOUR: 'HIDE_TOUR',
	SHOW_TOUR: 'SHOW_TOUR',
	JUMP_TO_SETTINGS_BIT: 'JUMP_TO_SETTINGS_BIT',
	HAVE_CLICKED_VIDEO_LINK: 'HAVE_CLICKED_VIDEO_LINK',
}

export const searchMutations = {
	SET_SEARCH_TERM: 'SET_SEARCH_TERM'
}